## Fichero de configuración para UjaCoin

spring.datasource.url: jdbc:mysql://localhost:3306/juandb
spring.datasource.username: root
spring.datasource.password: root

## spring.jpa.properties.javax.persistence.schema-generation.database.action: create
spring.jpa.properties.javax.persistence.schema-generation.database.action: create

spring.data.jpa.repositories.bootstrap-mode: default


