## Fichero de configuración para UjaCoin

spring.datasource.url: jdbc:mysql://localhost:3306/juandb
spring.datasource.username: root
spring.datasource.password: root
spring.jpa.properties.javax.persistence.schema-generation.database.action: create
spring.data.jpa.repositories.bootstrap-mode: default

##spring.datasource.url: jdbc:h2:~/h2db/h2juan2db;AUTO_SERVER=TRUE
##spring.jpa.show-sql: true
##jpa.generate-ddl: true
##spring.jpa.generate-ddl: true
##spring.jpa.properties.javax.persistence.schema-generation.database.action: drop-and-create

